Resources:
  MyDirectory:
  Type: AWS::DirectoryService::MicrosoftAD
  Properties: 
    CreateAlias: Boolean
    Edition: Standard
    EnableSso: True
    Name: "corp.permutaprop.com"
    Password: Test2020!Foo
    ShortName: corp.permutaprop.com
    VpcSettings: 
      SubnetIds: 
        - Ref: ^(subnet-[0-9a-f]{8}|subnet-[0-9a-f]{17})$
        - Ref: ^(subnet-[0-9a-f]{8}|subnet-[0-9a-f]{17})$
      VpcId: 
        Ref: ^(vpc-[0-9a-f]{8}|vpc-[0-9a-f]{17})$